In [1]:
# importing necessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

%matplotlib inline

In [2]:
kdn_df = pd.read_csv("../Dataset/kidney_disease.csv")

In [3]:
kdn_df.head(100)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,62.0,90.0,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,NaN,NaN,yes,no,no,good,yes,yes,ckd
96,96,60.0,80.0,1.010,1.0,1.0,NaN,normal,notpresent,notpresent,...,36,NaN,NaN,no,yes,yes,poor,no,no,ckd
97,97,65.0,60.0,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,32,9100,4.0,yes,yes,no,poor,yes,no,ckd
98,98,50.0,140.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,...,18,5800,2.3,yes,yes,no,poor,no,yes,ckd
99,99,56.0,180.0,NaN,0.0,4.0,NaN,abnormal,notpresent,notpresent,...,32,10400,4.2,yes,yes,no,poor,yes,no,ckd

In [4]:
kdn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [5]:
kdn_df.classification.unique()

array(['ckd', 'ckd\t', 'notckd'], dtype=object)

In [6]:
kdn_df.classification=kdn_df.classification.replace("ckd\t","ckd")

In [7]:
kdn_df.classification.unique()

array(['ckd', 'notckd'], dtype=object)

In [8]:
kdn_df.drop('id', axis = 1, inplace = True)

In [9]:
kdn_df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [103]:
kdn_df['classification'] = kdn_df['classification'].replace(['ckd', 'notckd'], [1, 0])
kdn_df = kdn_df.infer_objects()

In [105]:
kdn_df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,1
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,1
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,1
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,1
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,1

In [12]:
kdn_df.isnull().sum()

age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [13]:
df = kdn_df.dropna(axis = 0)
print(f"Before dropping all NaN values: {kdn_df.shape}")
print(f"After dropping all NaN values: {df.shape}")

Before dropping all NaN values: (400, 25)
After dropping all NaN values: (158, 25)

In [14]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,1
9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,29,12100,3.7,yes,yes,no,poor,no,yes,1
11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,32,4500,3.8,yes,yes,no,poor,yes,no,1
14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,16,11000,2.6,yes,yes,yes,poor,yes,no,1
20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,1

In [15]:
df.index = range(0,len(df),1)
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,1
1,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,29,12100,3.7,yes,yes,no,poor,no,yes,1
2,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,32,4500,3.8,yes,yes,no,poor,yes,no,1
3,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,16,11000,2.6,yes,yes,yes,poor,yes,no,1
4,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,1

In [16]:
for i in df['wc']:
    print(i)

6700
12100
4500
11000
9200
6900
9600
18900
7200
14600
6400
	6200
3800
9800
12500
5600
7000
15200
5000
16300
	8400
10500
15200
14600
7900
10900
12800
12400
19100
7500
16700
9600
26400
9800
8800
7400
12000
7500
15700
11500
5000
10200
5400
10400
9800
9100
6200
8300
9200
10700
9100
8400
4300
9400
5600
7200
8600
5000
10500
6800
9500
6900
7200
9000
5600
4700
6300
9400
5800
9100
5500
6700
5300
9800
7100
7000
10200
6300
8600
11000
7200
6200
9100
4300
7900
6900
11000
7500
8200
9400
8100
7000
10400
9600
7800
6700
8300
10700
7800
6700
4300
10700
7500
4700
7000
6700
7300
7700
5500
8100
7900
7200
7300
9900
7000
5800
6800
6300
7400
11000
5200
6000
5800
5400
10300
9300
10500
6700
9400
10300
9300
6500
10500
9200
8000
9700
9100
6400
5400
6500
6000
5100
11000
8000
5700
6200
9500
7200
6300
5800
6600
7400
9500
6700
7800
6600
7200
6800

In [17]:
# Replace values in the 'wc' column using .loc[]
df.loc[df['wc'].isin(["\t6200", "\t8400"]), 'wc'] = df['wc'].replace(["\t6200", "\t8400"], [6200, 8400])

In [18]:
for i in df['wc']:
    print(i)

6700
12100
4500
11000
9200
6900
9600
18900
7200
14600
6400
6200
3800
9800
12500
5600
7000
15200
5000
16300
8400
10500
15200
14600
7900
10900
12800
12400
19100
7500
16700
9600
26400
9800
8800
7400
12000
7500
15700
11500
5000
10200
5400
10400
9800
9100
6200
8300
9200
10700
9100
8400
4300
9400
5600
7200
8600
5000
10500
6800
9500
6900
7200
9000
5600
4700
6300
9400
5800
9100
5500
6700
5300
9800
7100
7000
10200
6300
8600
11000
7200
6200
9100
4300
7900
6900
11000
7500
8200
9400
8100
7000
10400
9600
7800
6700
8300
10700
7800
6700
4300
10700
7500
4700
7000
6700
7300
7700
5500
8100
7900
7200
7300
9900
7000
5800
6800
6300
7400
11000
5200
6000
5800
5400
10300
9300
10500
6700
9400
10300
9300
6500
10500
9200
8000
9700
9100
6400
5400
6500
6000
5100
11000
8000
5700
6200
9500
7200
6300
5800
6600
7400
9500
6700
7800
6600
7200
6800

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             158 non-null    float64
 1   bp              158 non-null    float64
 2   sg              158 non-null    float64
 3   al              158 non-null    float64
 4   su              158 non-null    float64
 5   rbc             158 non-null    object
 6   pc              158 non-null    object
 7   pcc             158 non-null    object
 8   ba              158 non-null    object
 9   bgr             158 non-null    float64
 10  bu              158 non-null    float64
 11  sc              158 non-null    float64
 12  sod             158 non-null    float64
 13  pot             158 non-null    float64
 14  hemo            158 non-null    float64
 15  pcv             158 non-null    object
 16  wc              158 non-null    object
 17  rc              158 non-null    object
 18  htn             158 non-null    object
 19  dm              158 non-null    object
 20  cad             158 non-null    object
 21  appet           158 non-null    object
 22  pe              158 non-null    object
 23  ane             158 non-null    object
 24  classification  158 non-null    int64
dtypes: float64(11), int64(1), object(13)
memory usage: 31.0+ KB

In [20]:
df['pcv']=df['pcv'].astype(int)
df['wc']=df['wc'].astype(int)
df['rc']=df['rc'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             158 non-null    float64
 1   bp              158 non-null    float64
 2   sg              158 non-null    float64
 3   al              158 non-null    float64
 4   su              158 non-null    float64
 5   rbc             158 non-null    object
 6   pc              158 non-null    object
 7   pcc             158 non-null    object
 8   ba              158 non-null    object
 9   bgr             158 non-null    float64
 10  bu              158 non-null    float64
 11  sc              158 non-null    float64
 12  sod             158 non-null    float64
 13  pot             158 non-null    float64
 14  hemo            158 non-null    float64
 15  pcv             158 non-null    int32
 16  wc              158 non-null    int32
 17  rc              158 non-null    float64
 18  htn             158 non-null    object
 19  dm              158 non-null    object
 20  cad             158 non-null    object
 21  appet           158 non-null    object
 22  pe              158 non-null    object
 23  ane             158 non-null    object
 24  classification  158 non-null    int64
dtypes: float64(12), int32(2), int64(1), object(10)
memory usage: 29.8+ KB

C:\Users\Romit\AppData\Local\Temp\ipykernel_2856\4219893708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pcv']=df['pcv'].astype(int)
C:\Users\Romit\AppData\Local\Temp\ipykernel_2856\4219893708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wc']=df['wc'].astype(int)
C:\Users\Romit\AppData\Local\Temp\ipykernel_2856\4219893708.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rc']=df['rc'].astype(float)

In [21]:
object_dtypes = df.select_dtypes(include = 'object')
object_dtypes.head()

        rbc        pc         pcc          ba  htn   dm  cad appet   pe  ane
0    normal  abnormal     present  notpresent  yes   no   no  poor  yes  yes
1  abnormal  abnormal     present  notpresent  yes  yes   no  poor   no  yes
2  abnormal  abnormal     present  notpresent  yes  yes   no  poor  yes   no
3    normal  abnormal     present     present  yes  yes  yes  poor  yes   no
4  abnormal  abnormal  notpresent  notpresent  yes  yes  yes  poor  yes  yes

In [22]:
dictonary = {
        "rbc": {
        "abnormal":1,
        "normal": 0,
    },
        "pc":{
        "abnormal":1,
        "normal": 0,
    },
        "pcc":{
        "present":1,
        "notpresent":0,
    },
        "ba":{
        "notpresent":0,
        "present": 1,
    },
        "htn":{
        "yes":1,
        "no": 0,
    },
        "dm":{
        "yes":1,
        "no":0,
    },
        "cad":{
        "yes":1,
        "no": 0,
    },
        "appet":{
        "good":1,
        "poor": 0,
    },
        "pe":{
        "yes":1,
        "no":0,
    },
        "ane":{
        "yes":1,
        "no":0,
    }
}

In [23]:
# Option 1: Manually cast columns to the correct type after replace
df = df.replace(dictonary)
df = df.astype({'wc': int})  # Example for converting 'wc' column to int

# Option 2: Use infer_objects after replace
df = df.replace(dictonary).infer_objects()

C:\Users\Romit\AppData\Local\Temp\ipykernel_2856\4263994129.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(dictonary)

In [24]:
# Display rows where the classification is 0 (indicating no CKD)
df_no_ckd = df[df['classification'] == 0]
df_no_ckd.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
43,40.0,80.0,1.025,0.0,0.0,0,0,0,0,140.0,...,48,10400,4.5,0,0,0,1,0,0,0
44,23.0,80.0,1.025,0.0,0.0,0,0,0,0,70.0,...,52,9800,5.0,0,0,0,1,0,0,0
45,45.0,80.0,1.025,0.0,0.0,0,0,0,0,82.0,...,46,9100,4.7,0,0,0,1,0,0,0
46,57.0,80.0,1.025,0.0,0.0,0,0,0,0,119.0,...,42,6200,6.2,0,0,0,1,0,0,0
47,51.0,60.0,1.025,0.0,0.0,0,0,0,0,99.0,...,49,8300,5.2,0,0,0,1,0,0,0

In [25]:
X = df.drop(['classification', 'sg', 'appet', 'rc', 'pcv', 'hemo', 'sod'], axis = 1)
Y = df['classification']

In [26]:
X.columns

Index(['age', 'bp', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc',
       'pot', 'wc', 'htn', 'dm', 'cad', 'pe', 'ane'],
      dtype='object')

In [27]:
X.head()

,age,bp,al,su,rbc,pc,pcc,ba,bgr,bu,sc,pot,wc,htn,dm,cad,pe,ane
0,48.0,70.0,4.0,0.0,0,1,1,0,117.0,56.0,3.8,2.5,6700,1,0,0,1,1
1,53.0,90.0,2.0,0.0,1,1,1,0,70.0,107.0,7.2,3.7,12100,1,1,0,0,1
2,63.0,70.0,3.0,0.0,1,1,1,0,380.0,60.0,2.7,4.2,4500,1,1,0,1,0
3,68.0,80.0,3.0,2.0,0,1,1,1,157.0,90.0,4.1,6.4,11000,1,1,1,1,0
4,61.0,80.0,2.0,0.0,1,1,0,0,173.0,148.0,3.9,5.2,9200,1,1,1,1,1

In [28]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: classification, dtype: int64

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2 , stratify=Y, random_state=2)

In [30]:
Y_train.count()

126

In [31]:
Y_train.value_counts()

classification
0    92
1    34
Name: count, dtype: int64

In [32]:
print(X.shape, X_train.shape,X_test.shape)

(158, 18) (126, 18) (32, 18)

In [33]:
classifier = svm.SVC(kernel='linear')

In [34]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [35]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [36]:
training_data_accuracy

0.9920634920634921

In [89]:
input_data = (65,80,2,0,0,1,1,0,150,36,1.2,4.5,7500,1,1,0,0,1)

# changing input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)
print(input_data_as_numpy_array)
# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
print(input_data_reshaped)

prediction = classifier.predict(input_data_reshaped)
print(prediction)


if (prediction[0] == 0):
  print("The Person does not have KIdney  Disease")

else:
  print("The Person has KIdney Disease")

[6.5e+01 8.0e+01 2.0e+00 0.0e+00 0.0e+00 1.0e+00 1.0e+00 0.0e+00 1.5e+02
 3.6e+01 1.2e+00 4.5e+00 7.5e+03 1.0e+00 1.0e+00 0.0e+00 0.0e+00 1.0e+00]
[[6.5e+01 8.0e+01 2.0e+00 0.0e+00 0.0e+00 1.0e+00 1.0e+00 0.0e+00 1.5e+02
  3.6e+01 1.2e+00 4.5e+00 7.5e+03 1.0e+00 1.0e+00 0.0e+00 0.0e+00 1.0e+00]]
[0]
The Person does not have KIdney  Disease

C:\Users\Romit\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [38]:
for column in X.columns:
  print(column)

age
bp
al
su
rbc
pc
pcc
ba
bgr
bu
sc
pot
wc
htn
dm
cad
pe
ane

In [39]:
import pickle

In [40]:
fileName = "../saveModels/Kidney.sav"

In [41]:
pickle.dump(classifier, open(fileName, 'wb'))

In [42]:
loaded_model = pickle.load(open(fileName, 'rb'))

In [93]:
input_data = (40,80,1.025,0,0,0,0,0,140,1,1,2,300,1,0,0,1,1)

# changing input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)


if (prediction[0] == 0):
  print("The Person does not have KIdney  Disease")

else:
  print("The Person has KIdney Disease")

[0]
The Person does not have KIdney  Disease

C:\Users\Romit\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(